<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\Data\aerial_-_18390 %281440p%29.mp4" />
    <None Include="wwwroot\Data\waves_-_70796 %281440p%29.mp4" />
    <None Include="wwwroot\Data\wave_-_19368 %281080p%29.mp4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseLibrary\BaseLibrary.csproj" />
    <ProjectReference Include="..\ClientLibrary\ClientLibrary.csproj" />
  </ItemGroup>

</Project>
